name: Test Golang
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      # Install dependencies and set up Go
      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: '1.19.2'
          go-version-file: engine/lambda-functions/go.mod
          cache: true

      # Run all the tests
      - name: Test
        working-directory: engine/lambda-functions
        run: go test -v ./...
